numpy arays and basics

In [1]:
import numpy as np
a = np.array([1, 2, 3])
print(a+2)

[3 4 5]


In [15]:
import numpy as np
var_a = 2
arr_1 = np.array([1,2,3])
arr_2 = np.array([1,1,1])

print (arr_1 + var_a*arr_2)


[3 4 5]


In [16]:
import numpy as np
data = [1, 2, 33]
t = 1+2+33
print(t)
a = np.array(data)
print(a)
b = np.mean(a)
print("Mean:",b)

36
[ 1  2 33]
Mean: 12.0


In [4]:
import numpy as np
s = np.mean([1, 3, 4, 5, 8])
print(s)

4.2


In [19]:
import numpy as np
data = [1, 3, 4, 5, 8]
c = np.array(data)
f = np.mean(c)
print(f)
weights = [1, 2, 3, 4, 5]
s = np.average(data,weights=weights)
print(s)

4.2
5.266666666666667


In [6]:
import numpy as np
temperature = [23, 25, 22, 26, 24, 27, 28]
weights = [1, 2, 3, 4, 5, 6, 7]
weights_average = np.average(temperature,weights=weights)
print(weights_average)

25.75


In [3]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr.shape, arr.dtype, arr[0][1])

(2, 2) int64 2


In [4]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
sum_result= np.array (a+b)
print(sum_result)

[2 4 6 8]


In [1]:
print(print)

<built-in function print>


In [16]:
py_List = [1,2] 
print("list Multiplication", py_List*2)

a = np.array ([1, 2])
print("Array Multiplication", a*2)


list Multiplication [1, 2, 1, 2]
Array Multiplication [2 4]


In [21]:
arr1 = np.array([11, 22, 33, 44])
arr2 = np.array([1, 2, 3, 4])
result1 = (arr1 - arr2)
result2 = (arr1 + arr2)

print("Arrays Subtraction", result1) 
print("Arrays Addition", result2)

Arrays Subtraction [10 20 30 40]
Arrays Addition [12 24 36 48]


### Creating Arrays from Scratch

In [2]:
import numpy as np
zero = np.zeros((2, 2))
print ("Zeros: \n", zero)

one = np.ones((3, 3))
print ("Ones: \n", one)

full = np.full((2, 2), 6)
print ("Full: \n", full)

random = np.random.random((3,3))
print ("Random: \n", random)

sequence = np.arange(0, 10, 2)
print("Squence: \n", sequence)


Zeros: 
 [[0. 0.]
 [0. 0.]]
Ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Full: 
 [[6 6]
 [6 6]]
Random: 
 [[0.50886147 0.69953751 0.51972529]
 [0.8983248  0.17237067 0.65958629]
 [0.48829577 0.54059923 0.51612563]]
Squence: 
 [0 2 4 6 8]


In [42]:
import numpy as np

one = np.ones([2, 2])
print (one)

zero = np.zeros([3, 3])
print (zero)

full = np.full([3, 3], 4)
print (full)

random = np.random.random([2,2])
print(random)

sequence = np.arange(1, 20, 2)
print (sequence)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[0.17742777 0.75149729]
 [0.85725136 0.17260727]]
[ 1  3  5  7  9 11 13 15 17 19]


### Matrixes, vectors 

In [3]:
import numpy as np

vector = np.array([1, 2, 3])
print(vector)

[1 2 3]


In [5]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix \n", matrix)

Matrix 
 [[1 2 3]
 [4 5 6]]
