### Numpy Operations

Array Indexing


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print ("Indexing:\n", arr[1:4])

Indexing:
 [2 3 4]


In [ ]:
import numpy as np
matrix = np.array([[11, 22, 33], #also callde 2d array
[44, 55, 66],
[77, 88, 99]])
print ("Matrix: \n", matrix[:, 2]) #leave row and focus on the colums
print ("Matrix: \n", matrix[2]) #leave colums and focus on the row
print ("Matrix: \n", matrix[1,2]) #focus on the mentioned line single item



Matrix: 
 [33 66 99]
Matrix: 
 [77 88 99]
Matrix: 
 66


### Average

In [2]:
import numpy as np
Data = np.array([5,10,15,20])
Average = np.average(Data)
print (Average)

12.5
